### ISSUE TITLE
Look into the issues column

### ISSUE THREAD

**Issue by Tushar-2510** [Sopra-Banking-Software-Interns/unified-automation-suite#115]
It is fetching issues based on user who initiates the issue

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @CodePrakhar, @Suvarchala-30, @navvay

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @CodePrakhar, @Suvarchala-30, @navvay

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @CodePrakhar, @Suvarchala-30, @navvay

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @CodePrakhar, @Suvarchala-30, @navvay

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @CodePrakhar, @Suvarchala-30, @navvay
