### ISSUE TITLE
Create a shell script for extracting open issues which are opened for more than 2 days & return the json data

### ISSUE THREAD

**Issue by Tushar-2510** [Sopra-Banking-Software-Interns/unified-automation-suite#116]

**Comment by CodePrakhar** [comment]
A gentle reminder, this issue has been opened from >2 days

**Comment by CodePrakhar** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @Tushar-2510

**Comment by CodePrakhar** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @Tushar-2510

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @Tushar-2510

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @Tushar-2510

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @Tushar-2510

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @Tushar-2510
