### ISSUE TITLE
Take open_issues.json & automatically commit reminder messages

### ISSUE THREAD

**Issue by Tushar-2510** [Sopra-Banking-Software-Interns/unified-automation-suite#117]

**Comment by CodePrakhar** [comment]
Reminder

**Comment by CodePrakhar** [comment]
Reminder

**Comment by CodePrakhar** [comment]
A gentle reminder, this issue has been opened from >2 days

**Comment by Tushar-2510** [comment]
reminder @CodePrakhar

**Comment by CodePrakhar** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @CodePrakhar

**Comment by CodePrakhar** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @Tushar-2510

**Comment by CodePrakhar** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @CodePrakhar, @Suvarchala-30

**Comment by CodePrakhar** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @CodePrakhar, @Suvarchala-30

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @CodePrakhar

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @CodePrakhar

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @CodePrakhar

**Comment by Riyu44** [comment]
A gentle reminder, this issue has been opened for more than 2 days. @CodePrakhar
